### PR TITLE
Added vBase with no styles

### PR DESCRIPTION
**Pull request by dolbex**
Sarah, thanks for the wonderful package. If we could add this vbase with no styles that would be awesome. loader does some things when styles is present but is empty that we have to avoid in our build routine and this would save us some highlight+delete time :)

### CODE REVIEW

**Comment by sdras** [comment]
Oh sure! Can you please add a reference to it in the readme? That's what people use as reference. After that, we're good to merge. Thanks!

**Comment by dolbex** [comment]
Awesome, I'll get this in there tonight!

**Comment by sdras** [comment]
Can you please resolve your conflicts? Thanks!

**Comment by dolbex** [comment]
Updated along with the README. Apologies on the delay.

**Comment by sdras** [comment]
Thank you!

**Pull request merged**
