### PR TITLE
Remove reference to plaintext.json

### PR DESCRIPTION
**Pull request by joshukraine**
I'm using this extension in Neovim with [coc-snippets](https://github.com/neoclide/coc-snippets). After installing, I get this error:

`[coc.nvim] Error on load snippets: ENOENT: no such file or directory, open '/Users/joshukraine/.config/coc/extensions/node_modules/vue-vscode-snippets/snippets/plaintext.json'`

I believe `snippets/plaintext.json` was renamed in this commit: https://github.com/sdras/vue-vscode-snippets/commit/499f5ef35d1a1c066fcdd5207d4f02e2bcaacba7

Removing the reference in package.json resolves the error.

Thank you for these great snippets! 🙂👍🏻

### CODE REVIEW

**Comment by sdras** [comment]
Thank you!

**Comment by sdras** [comment]
Thank you! Can you please fix the merge conflict? Appreciated

**Comment by joshukraine** [comment]
> Thank you! Can you please fix the merge conflict? Appreciated

OK, should be all set.

**Comment by sdras** [comment]
Thank you!

**Comment by Youzhigang** [comment]
wait for new release

**Pull request merged**
